version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/blam
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
